### ISSUE TITLE
code example request

### ISSUE THREAD

**Issue by elitepleb** [LWSS/McDota#12]
Any chance of seeing some more code examples?
Like how to cast spells, use items, get hero inventory/stats/cooldowns?
So far i have only managed to make a simple lasthit marker.
But that relies on me setting the ent index myself via a convar since engine->GetLocalPlayer() returns the player, not the hero index.
And it's inaccurate since i only found the minimal base damage available.

here's the code if anyone wants it(Esp.cpp)
```
if(entity->C_BaseEntity__GetHealth() == 0)
      continue;

CDotaBaseNPC *Localplayer = (CDotaBaseNPC *)entitySystem->GetBaseEntity(mc_index->GetInt());

if(Localplayer) {
  if( strstr(entity->Schema_DynamicBinding()->bindingName, "C_DOTA_BaseNPC_Creep") != nullptr ) {
    int x, y;
    GetVectorInScreenSpace(*entity->C_BaseEntity__WorldSpaceCenter(), x, y, nullptr);
    if(entity->C_BaseEntity__GetHealth() <= Localplayer->C_DOTA_BaseNPC__GetDamageMin())
      surface->DrawColoredCircle(x, y-20, 40, 0, 0, 255, 255);
  }
}
```

**Comment by LWSS** [comment]
Hero inventory we don't really have yet... You could iterate entities and look for owner though. 

Want to get which hero is yours? You could also iterate and look for owner.... ( I think the function is something like GetAssignedHero() in the game's code ).

If you want to have your hero do something, you need to send an order, checkout prepareunitorders hook.

You found GetDamageMin() but there's also GetDamageMax(), the hit is rolled randomly between those 2 numbers on the server.

This cheat is very experimental and I mostly spend time reversing stuff and looking around. ( meta-development? )

If you have any more feature ideas, I could give you an idea, also checking out lua scripts might be a decent idea because there's probably stuff you can paste somewhere and it's somewhat documented by valve.

**Comment by elitepleb** [comment]
Thanks for the info.

Right now, all i'm missing is how to interact with PrepareUnitOrders, since the cast post redirection example only modifies a cast spell and doesn't show how to cast one.
Just showing how to cast a spell would let me make some basic things like a zues killstealer.

Just finding the netvars dump helped me get a lot of stuff i was missing.
Most ownership indexes are passed by handles, but i found that i can get the index with a bitwise AND like this GetBaseEntity(handle & 0xFFF), so getting entities isn't a problem anymore.

Lua doesn't seem to be a great path since there's not a lot you can with it.
At least according to the only thread i found talking about it https://www.unknowncheats.me/forum/1329553-post20.html

I guess i'll just manage with what i have now, since i'm hopeless when it comes to reversing stuff with no symbol info(especially now that i have no access to ida or experience with linux re tools :d)

And if anyone wants it, i found a better way to see if i can lasthit an ent.
```
if(entity->C_BaseEntity__GetActualHealth() <= Localplayer->C_DOTA_BaseNPC__GetDamageMin() + Localplayer->C_DOTA_BaseNPC__GetDamageBonus())
```
GetActualHealth() seems to be your hp value divided by your damage multiplier based on the armor damage multiplier formula: 1 - ((0.052 × armor) ÷ (0.9 + 0.048 × |armor|)).
And GetDamageBonus() gets the item damage bonus for you. It also returns an int and not a float.
At least according to the netvars.

**Comment by LWSS** [comment]
just turn on log prepareunitorders and check the log file, you'll see how the arguments are set up. Many of them are optional.

**Comment by elitepleb** [comment]
Ok, thanks.
