### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by Jermany** [LWSS/McDota#60]
just a heads up for anyone looking at protobufs, as of the new player experience update valve are now on 3.15.3
https://i.imgur.com/YqImJcG.png
using 3.7.0 will now cause random segfaults

**Comment by LWSS** [comment]
you get the string allocations working?

**Comment by LWSS** [comment]
I have everything working, haven't pushed yet :^))) , except for the string allocations on protobufs. I remember I had issues with it a long time ago, probably something dumb

**Comment by Jermany** [comment]
> I have everything working, haven't pushed yet :^))) , except for the string allocations on protobufs. I remember I had issues with it a long time ago, probably something dumb

huh, sorry i havent encountered any issues like that, pretty much worked out the box for me, but nice to hear about your update! i used your code for the network messages, thank you very much for that. would you like to talk on discord sometime?

**Comment by LWSS** [comment]
There we go, working now. The issue was a combination of 3 things
* The Network Protobuf Binder
* Not using g_pMemAlloc (tc_delete)
* Not using the proper std::string ABI

Luckily my adventures in kisak-strike prepared me for this moment and everything is back working.

>pretty much worked out the box for me

This is what I thought too, but try editing/adding strings. It *might* work if you used GCC 4.
